# Generated by Django 3.2.3 on 2021-05-30 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=100, verbose_name='stream name')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
                ('stream_key', models.CharField(max_length=100, verbose_name='stream key')),
                ('hls_key', models.CharField(default='', max_length=100, verbose_name='stream url')),
                ('likes', models.IntegerField(default=0, verbose_name='likes')),
                ('is_streaming', models.BooleanField(default=False, verbose_name='is streaming')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
    ]
