# Generated by Django 3.2.3 on 2021-05-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('stream_key', models.CharField(max_length=250)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
