# Generated by Django 3.2.3 on 2021-05-28 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streamdapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='username',
        ),
        migrations.AddField(
            model_name='stream',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
