# Generated by Django 3.2.3 on 2021-05-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('streamdapp', '0002_auto_20210528_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='stream_url',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='stream',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
