# Generated by Django 3.2.3 on 2021-05-28 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streamdapp', '0003_auto_20210528_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='stream_url',
        ),
        migrations.AddField(
            model_name='stream',
            name='hls_key',
            field=models.CharField(default='', max_length=250, verbose_name='stream url'),
        ),
        migrations.AddField(
            model_name='stream',
            name='is_streaming',
            field=models.BooleanField(default=False, verbose_name='is streaming'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='likes'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_key',
            field=models.CharField(max_length=250, verbose_name='stream key'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_name',
            field=models.CharField(max_length=250, verbose_name='stream name'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
