# Generated by Django 3.2.3 on 2021-05-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamdapp', '0004_auto_20210528_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='hls_key',
            field=models.CharField(default='', max_length=100, verbose_name='stream url'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_key',
            field=models.CharField(max_length=100, verbose_name='stream key'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_name',
            field=models.CharField(max_length=100, verbose_name='stream name'),
        ),
    ]
